spring.application.name=escola

# Usando H2 em memória para facilitar o desenvolvimento local
spring.datasource.url=jdbc:h2:mem:tabajara_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Se quiser usar PostgreSQL local, descomente e ajuste abaixo
#spring.datasource.url=jdbc:postgresql://localhost:5432/tabajara_db
#spring.datasource.username=postgres
#spring.datasource.password=postdba
#spring.datasource.driver-class-name=org.postgresql.Driver

#Limpar o cache para a execução do thymeleaf
spring.thymeleaf.cache=false
